name: Optima MacOS Analyzer
on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  OptimaMacOSScan:
    runs-on: macos-13-xlarge
    steps:
      - uses: actions/checkout@v4
      - uses: vwdfive/optima-actions@mac
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          toolstation-token: ${{ secrets.OPTIMA_TOKEN }}
          
